const initialStates = {
   doctorRecordPatientId: null,
   isLoading: false,
   //Patient Dashboard
   tempMedications: [],
   reloadMedications: false,
   message: {
      show: false,
      msg: 'Error me',
      state: 0,
   },
   okToRoute: false,
   user: {
      name: '',
      id_patient: '',
      id_guardian: '',
   },
   profile: {
      user_email: '',
      first_name: '',
      house_address: '',
      id_patient: '',
      id_doctor: '',
      id_guardian: '',
      id_number: '',
      last_name: '',
      middle_name: '',
      nationality: '',
      phone_number: '',
      person_image: '',
      date_of_birth: '',
      gender: '',
   },
   health: {
      blood_group: '',
      blood_pressure: '',
      blood_sugar: '',
      height: '',
      last_visit: '',
      pulse: '',
      respiratory_rate: '',
      weight: '',
   },
   guardian: {
      first_name: '',
      middle_name: '',
      last_name: '',
      user_email: '',
      date_of_birth: '',
      house_address: '',
      phone_number: '',
      id_number: '',
      gender: '',
   },
   doctorAppointment: {},
   doctorToChatWith: '',
   appointmentDates: [],
   isPatientAuth: false,

   // Doctor Dashboard
   isDoctorAuth: false,
   doctorProfile: {
      first_name: '',
      middle_name: '',
      last_name: '',
      user_email: '',
      date_of_birth: '',
      gender: '',
      house_address: '',
      license_number: '',
      doctor_specialties: '',
      hospital_code: '',
      doctor_ratings: '',
      person_image: '',
      id_doctor: '',
   },
   patientToChatWith: '',
   allPendingAppointments: [],
   messagePatientState: false,
};

export default initialStates;
