export const SET_NAME = 'SET_NAME';
export const SET_PROFILE_INFO = 'SET_PROFILE_INFO';
export const SET_HEALTH_INFO = 'SET_HEALTH_INFO';
export const SET_GUARDIAN_INFO = 'SET_GUARDIAN_INFO';
export const SET_REPORTS = 'SET_REPORTS';

export const SET_DOCTOR_PROFILE_INFO = 'SET_DOCTOR_PROFILE_INFO';
