export const SET_NAME = 'SET_NAME';
export const SET_PROFILE_INFO = 'SET_PROFILE_INFO';
export const SET_HEALTH_INFO = 'SET_HEALTH_INFO';
export const SET_GUARDIAN_INFO = 'SET_GUARDIAN_INFO';
export const SET_REPORTS = 'SET_REPORTS';
export const SET_APPOINTMENT_DOCTOR = 'SET_APPOINTMENT_DOCTOR';
export const CLEAR_APPOINTMENT_DOCTOR = 'CLEAR_APPOINTMENT_DOCTOR';
export const SET_CHAT_WITH_DOCTOR = 'SET_CHAT_WITH_DOCTOR';
// Doctor Dashboard
export const SET_DOCTOR_PROFILE_INFO = 'SET_DOCTOR_PROFILE_INFO';
export const SET_PATIENT_TO_CHAT_WITH = 'SET_PATIENT_TO_CHAT_WITH';
